
name: Blog Index Builder

on:
  push:
    paths:
      - 'posts/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Markdown files
        run: |
          python scripts/validate_frontmatter.py || echo "::warning::Some posts have invalid frontmatter"

      - name: Generate index
        run: python scripts/generate_index.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posts/list.json
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Auto-update post index [skip ci]" && git push)
